{% set name = "sysrsync" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sysrsync-{{ version }}.tar.gz
  sha256: 435f9eb620e68ffb18ca5cbad32b113396a432361c7722038eab65c97dd83bd5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.6.0,<4.0.0
    - toml >=0.10.0,<0.11.0

test:
  imports:
    - sysrsync
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gchamon/sysrsync
  summary: Simple and safe python wrapper for calling system rsync
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - johanneskoester
